Update home.ko.yml_version 1
mgmodell/CoLab pull request #26
Opened 2024-10-18 16:39 UTC by misunrina

Could you please check if this is the correct way of translating the content?

2024-10-18 16:43 UTC, mgmodell commented
I will take a look at this and the previous in relation to #25 as soon as I am able.

2024-10-18 16:45 UTC, misunrina commented
I have entered more content for translation on GitHub. I hope I have
utilized this system correctly.


Misun Modell


On Fri, Oct 18, 2024 at 12:44 PM Micah Gideon Modell <
***@***.***> wrote:

> I will take a look at this and the previous in relation to #25
> <https://github.com/mgmodell/CoLab/issues/25> as soon as I am able.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mgmodell/CoLab/pull/26#issuecomment-2422862951>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BMGHBOA52ZP6FZIZU3C7CFDZ4E3FZAVCNFSM6AAAAABQGJ7S3CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMRSHA3DEOJVGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-19 19:28 UTC, mgmodell requested changes
Assuming that the translated content itself is correct (and I cannot validate that), these additions do appear as though they would work if the comments I've provided are addressed.

2024-10-19 19:28 UTC, mgmodell commented on config/locales/home.ko.yml
> +    이 이메일은 현재 대기 중인 할 일이 있음을 상기시켜 드리기 위해 발송되었습니다.
I cannot tell what this is attached to and it appears to be a duplication of the item below. Does this belong here?

2024-10-23 01:05 UTC, merged